const APP_VERSION = '2.2.9';
const VERSION_FILE = './version.json';
const STYLE_ID = 'vestope-version-status-style';
const BAR_ID = 'vestope-global-version-bar';
const MODAL_ID = 'vestope-update-modal';
const RECOVERY_ID = 'vestope-recovery-modal';
let rollbackActive = localStorage.getItem('vestope:rollback-active') === '1';
let lastStatus = rollbackActive ? 'rollback' : (navigator.onLine ? 'current' : 'offline');
let versionCheckInFlight = false;
let updateBusy = false;
let updateDeferred = false;
let lastRemoteVersion = null;
let lastUpdateError = '';

function installStyles(){
  if(document.getElementById(STYLE_ID))return;
  const style=document.createElement('style');style.id=STYLE_ID;style.textContent=`
    #app > footer,#app .auth-card > footer{display:none!important}
    .app-version-bar{position:fixed;left:0;right:0;bottom:0;z-index:9999;min-height:30px;padding:5px 14px calc(5px + env(safe-area-inset-bottom));box-sizing:border-box;display:flex;align-items:center;justify-content:center;background:rgba(255,255,255,.96);border-top:1px solid #dbe8f2;box-shadow:0 -4px 16px rgba(41,73,105,.08);font:600 12px/1.2 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#61758d;backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px)}
    .app-version-footer{display:inline-flex;align-items:center;justify-content:center;gap:7px;flex-wrap:wrap}.app-version-status{font-weight:800;border:0;background:transparent;font:inherit;color:inherit;padding:0;cursor:default}.app-version-status.update,.app-version-status.rollback{color:#1769aa;cursor:pointer;text-decoration:underline;text-underline-offset:2px}.app-version-status.current{color:#28754a}.app-version-status.offline{color:#7b8da1}.app-version-mark{width:15px;height:15px;display:inline-grid;place-items:center;border-radius:50%;font-size:10px;font-weight:900;line-height:1;background:#20b55a;color:#fff}.app-version-status.offline .app-version-mark{background:#7b8da1}.app-version-status.update .app-version-mark,.app-version-status.rollback .app-version-mark{background:#1769aa}.app-version-restart{width:22px;height:22px;border:1px solid #d4e2ee;border-radius:50%;background:#fff;color:#55708b;font:800 14px/1 system-ui;cursor:pointer;margin-left:3px}.app-version-restart:hover{background:#eef6fc}
    .vestope-version-overlay{position:fixed;inset:0;z-index:100000;background:rgba(20,38,57,.58);backdrop-filter:blur(7px);-webkit-backdrop-filter:blur(7px);display:flex;align-items:center;justify-content:center;padding:24px;box-sizing:border-box}.vestope-version-modal{width:min(440px,100%);box-sizing:border-box;background:#fff;border:1px solid #dce8f2;border-radius:28px;box-shadow:0 24px 70px rgba(13,38,61,.28);padding:30px 26px 26px;text-align:center}.vestope-version-icon{width:64px;height:64px;margin:0 auto 16px;border-radius:20px;background:#e9f5ff;color:#1769aa;display:grid;place-items:center;font-size:30px;font-weight:900}.vestope-version-modal .eyebrow{margin:0 0 8px}.vestope-version-modal h2{margin:0 0 10px;color:#17263d;font-size:30px;line-height:1.08}.vestope-version-modal p{margin:0 0 22px;color:#61758d;font-size:16px;line-height:1.45}.vestope-version-primary{width:100%;min-height:54px;border:0;border-radius:28px;background:#20b55a;color:#fff;font:800 17px/1 system-ui;cursor:pointer;box-shadow:0 8px 24px rgba(32,181,90,.2)}.vestope-version-primary:disabled{opacity:.65;cursor:wait}.vestope-version-secondary{width:100%;min-height:48px;border:1px solid #d8e5ef;border-radius:24px;background:#f7fbfe;color:#45627c;font:800 15px/1 system-ui;cursor:pointer;margin-top:10px}.vestope-error-text{font-size:13px!important;color:#8a4a4a!important;margin-top:12px!important}body{padding-bottom:34px}
  `;document.head.appendChild(style);
}
function ensureBar(){let bar=document.getElementById(BAR_ID);if(bar)return bar;bar=document.createElement('div');bar.id=BAR_ID;bar.className='app-version-bar';bar.setAttribute('role','status');bar.setAttribute('aria-live','polite');document.body.appendChild(bar);return bar}
function isAppBusy(){return Boolean(document.querySelector('.ride-card,.report-card,#phase5ReportForm'))}
function render(status=lastStatus){const bar=ensureBar();const map={current:['✓','AKTUÁLNÍ','current'],offline:['•','OFFLINE','offline'],update:['↑','NOVÁ VERZE K DISPOZICI','update'],rollback:['↶','ZÁLOŽNÍ VERZE','rollback']};const [icon,label,cls]=map[status]||map.current;bar.innerHTML=`<span class="app-version-footer"><span>VeStope.cz</span><span>·</span><span>verze ${APP_VERSION}</span><span>·</span><button class="app-version-status ${cls}" id="vestopeVersionStatus" type="button"><span class="app-version-mark">${icon}</span> ${label}</button><button class="app-version-restart" id="vestopeRestart" type="button" title="Restartovat aplikaci" aria-label="Restartovat aplikaci">↻</button></span>`;document.getElementById('vestopeVersionStatus')?.addEventListener('click',()=>{if(lastStatus==='update'||lastStatus==='rollback')openUpdateModal()});document.getElementById('vestopeRestart')?.addEventListener('click',restartApp)}
function removeModal(id){document.getElementById(id)?.remove()}
function openUpdateModal(){if((lastStatus!=='update'&&lastStatus!=='rollback')||document.getElementById(MODAL_ID)||updateBusy)return;if(isAppBusy()){updateDeferred=true;return}const overlay=document.createElement('div');overlay.id=MODAL_ID;overlay.className='vestope-version-overlay';overlay.innerHTML=`<div class="vestope-version-modal" role="dialog" aria-modal="true"><div class="vestope-version-icon">↑</div><div class="eyebrow">AKTUALIZACE APLIKACE</div><h2>Nová verze je připravena.</h2><p>VeStope.cz má připravenou novou verzi <strong>${escapeHtml(lastRemoteVersion||'')}</strong>. Pro pokračování aplikaci aktualizuj.</p><button class="vestope-version-primary" id="vestopeUpdateButton" type="button">AKTUALIZOVAT</button></div>`;document.body.appendChild(overlay);document.getElementById('vestopeUpdateButton')?.addEventListener('click',performUpdate)}
function restartApp(){window.location.reload()}
async function getRegistration(){if(!('serviceWorker'in navigator))return null;return navigator.serviceWorker.getRegistration('./')||navigator.serviceWorker.ready}
async function performUpdate(){if(updateBusy||!navigator.onLine)return;if(isAppBusy()){updateDeferred=true;return}updateBusy=true;lastUpdateError='';const button=document.getElementById('vestopeUpdateButton');if(button){button.disabled=true;button.textContent='AKTUALIZUJI…'}try{const registration=await getRegistration();if(!registration)throw new Error('Aktualizace Service Workeru není dostupná.');await registration.update();const worker=registration.waiting||registration.installing;if(worker){localStorage.removeItem('vestope:rollback-active');worker.postMessage({type:'SKIP_WAITING'});}setTimeout(()=>window.location.reload(),1500)}catch(error){updateBusy=false;lastUpdateError=error?.message||'Aktualizaci se nepodařilo dokončit.';if(button){button.disabled=false;button.textContent='ZKUSIT ZNOVU'}const modal=document.querySelector(`#${MODAL_ID} .vestope-version-modal`);if(modal&&!modal.querySelector('.vestope-error-text'))modal.insertAdjacentHTML('beforeend',`<p class="vestope-error-text">${escapeHtml(lastUpdateError)}</p>`)}}
async function checkVersion(){if(versionCheckInFlight)return;if(!navigator.onLine){lastStatus=rollbackActive?'rollback':'offline';render();return}versionCheckInFlight=true;try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),7000);const response=await fetch(`${VERSION_FILE}?check=${Date.now()}`,{cache:'no-store',signal:controller.signal});clearTimeout(timeout);if(!response.ok)throw new Error('version check failed');const remote=await response.json();lastRemoteVersion=String(remote.version||'');if(rollbackActive)lastStatus='rollback';else{lastStatus=lastRemoteVersion===APP_VERSION?'current':'update';if(lastStatus==='update')openUpdateModal()}render()}catch(_){lastStatus=rollbackActive?'rollback':(navigator.onLine?'current':'offline');render()}finally{versionCheckInFlight=false}}
function escapeHtml(value){return String(value??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]||c))}
function maybeShowDeferredUpdate(){if(updateDeferred&&!isAppBusy()&&(lastStatus==='update'||lastStatus==='rollback')){updateDeferred=false;openUpdateModal()}}
installStyles();render();window.addEventListener('online',checkVersion);window.addEventListener('offline',()=>{lastStatus=rollbackActive?'rollback':'offline';render();removeModal(MODAL_ID)});setTimeout(checkVersion,500);setInterval(checkVersion,5*60*1000);setInterval(maybeShowDeferredUpdate,2000);
