const APP_VERSION = '2.2.8';
const VERSION_FILE = './version.json';
const STYLE_ID = 'vestope-version-status-style';
const BAR_ID = 'vestope-global-version-bar';
const MODAL_ID = 'vestope-update-modal';
const RECOVERY_ID = 'vestope-recovery-modal';
let rollbackActive = localStorage.getItem('vestope:rollback-active') === '1';
let lastStatus = rollbackActive ? 'rollback' : (navigator.onLine ? 'current' : 'offline');
let versionCheckInFlight = false;
let updateBusy = false;
let updateDeferred = false;
let lastRemoteVersion = null;
let lastUpdateError = '';

function installStyles(){
  if(document.getElementById(STYLE_ID))return;
  const style=document.createElement('style');style.id=STYLE_ID;style.textContent=`
    #app > footer,#app .auth-card > footer{display:none!important}
    .app-version-bar{position:fixed;left:0;right:0;bottom:0;z-index:9999;min-height:30px;padding:5px 14px calc(5px + env(safe-area-inset-bottom));box-sizing:border-box;display:flex;align-items:center;justify-content:center;background:rgba(255,255,255,.96);border-top:1px solid #dbe8f2;box-shadow:0 -4px 16px rgba(41,73,105,.08);font:600 12px/1.2 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#61758d;backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px)}
    .app-version-footer{display:inline-flex;align-items:center;justify-content:center;gap:7px;flex-wrap:wrap}.app-version-status{font-weight:800;border:0;background:transparent;font:inherit;color:inherit;padding:0;cursor:default}.app-version-status.update,.app-version-status.rollback{color:#1769aa;cursor:pointer;text-decoration:underline;text-underline-offset:2px}.app-version-status.current{color:#28754a}.app-version-status.offline{color:#7b8da1}.app-version-mark{width:15px;height:15px;display:inline-grid;place-items:center;border-radius:50%;font-size:10px;font-weight:900;line-height:1;background:#20b55a;color:#fff}.app-version-status.offline .app-version-mark{background:#7b8da1}.app-version-status.update .app-version-mark,.app-version-status.rollback .app-version-mark{background:#1769aa}.app-version-restart{width:22px;height:22px;border:1px solid #d4e2ee;border-radius:50%;background:#fff;color:#55708b;font:800 14px/1 system-ui;cursor:pointer;margin-left:3px}.app-version-restart:hover{background:#eef6fc}
    .vestope-version-overlay{position:fixed;inset:0;z-index:100000;background:rgba(20,38,57,.58);backdrop-filter:blur(7px);-webkit-backdrop-filter:blur(7px);display:flex;align-items:center;justify-content:center;padding:24px;box-sizing:border-box}.vestope-version-modal{width:min(440px,100%);box-sizing:border-box;background:#fff;border:1px solid #dce8f2;border-radius:28px;box-shadow:0 24px 70px rgba(13,38,61,.28);padding:30px 26px 26px;text-align:center}.vestope-version-icon{width:64px;height:64px;margin:0 auto 16px;border-radius:20px;background:#e9f5ff;color:#1769aa;display:grid;place-items:center;font-size:30px;font-weight:900}.vestope-version-modal .eyebrow{margin:0 0 8px}.vestope-version-modal h2{margin:0 0 10px;color:#17263d;font-size:30px;line-height:1.08}.vestope-version-modal p{margin:0 0 22px;color:#61758d;font-size:16px;line-height:1.45}.vestope-version-primary{width:100%;min-height:54px;border:0;border-radius:28px;background:#20b55a;color:#fff;font:800 17px/1 system-ui;cursor:pointer;box-shadow:0 8px 24px rgba(32,181,90,.2)}.vestope-version-primary:disabled{opacity:.65;cursor:wait}.vestope-version-secondary{width:100%;min-height:48px;border:1px solid #d8e5ef;border-radius:24px;background:#f7fbfe;color:#45627c;font:800 15px/1 system-ui;cursor:pointer;margin-top:10px}.vestope-version-small{margin-top:14px!important;margin-bottom:0!important;font-size:13px!important}.vestope-version-modal.recovery{text-align:left}.vestope-version-modal.recovery h2{font-size:28px}.vestope-recovery-actions{display:grid;gap:10px}.vestope-error-text{font-size:13px!important;color:#8a4a4a!important;margin-top:12px!important}
    body{padding-bottom:34px}
  `;document.head.appendChild(style);
}
function ensureBar(){let bar=document.getElementById(BAR_ID);if(bar)return bar;bar=document.createElement('div');bar.id=BAR_ID;bar.className='app-version-bar';bar.setAttribute('role','status');bar.setAttribute('aria-live','polite');document.body.appendChild(bar);return bar}
function isAppBusy(){return Boolean(document.querySelector('.ride-card,.report-card,#phase5ReportForm'))}
function render(status=lastStatus){const bar=ensureBar();const map={current:['✓','AKTUÁLNÍ','current'],offline:['•','OFFLINE','offline'],update:['↑','NOVÁ VERZE K DISPOZICI','update'],rollback:['↶','ZÁLOŽNÍ VERZE','rollback']};const [icon,label,cls]=map[status]||map.current;bar.innerHTML=`<span class="app-version-footer"><span>VeStope.cz</span><span>·</span><span>verze ${APP_VERSION}</span><span>·</span><button class="app-version-status ${cls}" id="vestopeVersionStatus" type="button"><span class="app-version-mark">${icon}</span> ${label}</button><button class="app-version-restart" id="vestopeRestart" type="button" title="Restartovat aplikaci" aria-label="Restartovat aplikaci">↻</button></span>`;document.getElementById('vestopeVersionStatus')?.addEventListener('click',()=>{if(lastStatus==='update'||lastStatus==='rollback')openUpdateModal()});document.getElementById('vestopeRestart')?.addEventListener('click',restartApp)}
function removeModal(id){document.getElementById(id)?.remove()}
function openUpdateModal(){if((lastStatus!=='update'&&lastStatus!=='rollback')||document.getElementById(MODAL_ID)||updateBusy)return;if(isAppBusy()){updateDeferred=true;return}const overlay=document.createElement('div');overlay.id=MODAL_ID;overlay.className='vestope-version-overlay';overlay.innerHTML=`<div class="vestope-version-modal" role="dialog" aria-modal="true" aria-labelledby="vestopeUpdateTitle"><div class="vestope-version-icon">↑</div><div class="eyebrow">AKTUALIZACE APLIKACE</div><h2 id="vestopeUpdateTitle">Nová verze je připravena.</h2><p>VeStope.cz má připravenou novou verzi <strong>${escapeHtml(lastRemoteVersion||'')}</strong>. Pro pokračování aplikaci aktualizuj.</p><button class="vestope-version-primary" id="vestopeUpdateButton" type="button">AKTUALIZOVAT</button></div>`;document.body.appendChild(overlay);document.getElementById('vestopeUpdateButton')?.addEventListener('click',performUpdate)}
function openRecoveryModal(errorText=''){if(document.getElementById(RECOVERY_ID)||document.getElementById(MODAL_ID))return;const overlay=document.createElement('div');overlay.id=RECOVERY_ID;overlay.className='vestope-version-overlay';overlay.innerHTML=`<div class="vestope-version-modal recovery" role="dialog" aria-modal="true"><div class="vestope-version-icon">↻</div><div class="eyebrow">OBNOVA APLIKACE</div><h2>Aplikace se nespustila správně.</h2><p>Tvoje uložená data a rozpracované reporty zůstávají v zařízení. Můžeš aplikaci jednoduše restartovat nebo obnovit předchozí funkční verzi.</p>${errorText?`<p class="vestope-error-text">${escapeHtml(errorText)}</p>`:''}<div class="vestope-recovery-actions"><button class="vestope-version-primary" id="vestopeRecoveryRestart" type="button">RESTARTOVAT APLIKACI</button><button class="vestope-version-secondary" id="vestopeRollback" type="button">OBNOVIT PŘEDCHOZÍ VERZI</button></div></div>`;document.body.appendChild(overlay);document.getElementById('vestopeRecoveryRestart')?.addEventListener('click',restartApp);document.getElementById('vestopeRollback')?.addEventListener('click',rollbackApp)}
function restartApp(){window.location.reload()}
async function getRegistration(){if(!('serviceWorker'in navigator))return null;return navigator.serviceWorker.getRegistration('./')||navigator.serviceWorker.ready}
function waitForInstallation(registration,timeoutMs=30000){return new Promise((resolve,reject)=>{let worker=registration.installing;if(registration.waiting)return resolve(registration.waiting);if(!worker){const timer=setTimeout(()=>reject(new Error('Novou verzi se nepodařilo připravit. Zkontroluj připojení a zkus to znovu.')),timeoutMs);const poll=setInterval(()=>{if(registration.waiting){clearInterval(poll);clearTimeout(timer);resolve(registration.waiting);}else if(registration.installing){clearInterval(poll);clearTimeout(timer);worker=registration.installing;watch(worker);}},200);function watch(sw){const timer2=setTimeout(()=>reject(new Error('Příprava aktualizace trvá příliš dlouho. Zkontroluj připojení a zkus to znovu.')),timeoutMs);sw.addEventListener('statechange',()=>{if(sw.state==='installed'){clearTimeout(timer2);resolve(sw);}else if(sw.state==='redundant'){clearTimeout(timer2);reject(new Error('Novou verzi se nepodařilo nainstalovat. Stávající verze zůstává zachována.'))}})}return;}watch(worker);function watch(sw){const timer=setTimeout(()=>reject(new Error('Příprava aktualizace trvá příliš dlouho. Zkontroluj připojení a zkus to znovu.')),timeoutMs);sw.addEventListener('statechange',()=>{if(sw.state==='installed'){clearTimeout(timer);resolve(registration.waiting||sw);}else if(sw.state==='redundant'){clearTimeout(timer);reject(new Error('Novou verzi se nepodařilo nainstalovat. Stávající verze zůstává zachována.'))}})}})}
async function performUpdate(){if(updateBusy||!navigator.onLine)return;if(isAppBusy()){updateDeferred=true;return}updateBusy=true;lastUpdateError='';const button=document.getElementById('vestopeUpdateButton');if(button){button.disabled=true;button.textContent='PŘIPRAVUJI AKTUALIZACI…'}try{const registration=await getRegistration();if(!registration)throw new Error('Aktualizace Service Workeru není dostupná.');if(!registration.waiting){await registration.update();}const waiting=await waitForInstallation(registration,30000);if(!waiting)throw new Error('Novou verzi se nepodařilo připravit.');if(button)button.textContent='AKTUALIZUJI…';localStorage.removeItem('vestope:rollback-active');const reloadPromise=new Promise(resolve=>{let settled=false;const finish=()=>{if(settled)return;settled=true;resolve()};const handler=()=>{navigator.serviceWorker.removeEventListener('controllerchange',handler);finish()};navigator.serviceWorker.addEventListener('controllerchange',handler);setTimeout(finish,12000)});waiting.postMessage({type:'SKIP_WAITING'});await reloadPromise;window.location.reload()}catch(error){updateBusy=false;lastUpdateError=error?.message||'Aktualizaci se nepodařilo dokončit.';if(button){button.disabled=false;button.textContent='AKTUALIZOVAT'}const note=document.querySelector(`#${MODAL_ID} .vestope-version-modal .vestope-error-text`);if(note)note.textContent=lastUpdateError;else{const body=document.querySelector(`#${MODAL_ID} .vestope-version-modal p`);body?.insertAdjacentHTML('afterend',`<p class="vestope-error-text">${escapeHtml(lastUpdateError)}</p>`)}}}
async function rollbackApp(){try{const controller=navigator.serviceWorker?.controller;if(!controller)throw new Error('Záložní verze není dostupná.');localStorage.setItem('vestope:rollback-active','1');controller.postMessage({type:'ROLLBACK'});setTimeout(()=>window.location.reload(),700)}catch(error){localStorage.removeItem('vestope:rollback-active');alert(error?.message||'Obnovení se nepodařilo.')}}
async function checkVersion(){if(versionCheckInFlight)return;if(!navigator.onLine){lastStatus=rollbackActive?'rollback':'offline';render();return}versionCheckInFlight=true;try{const registration=await getRegistration();if(registration?.waiting){lastStatus='update';lastRemoteVersion=lastRemoteVersion||'nová verze';render();if(!rollbackActive)openUpdateModal();return}const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),7000);const response=await fetch(`${VERSION_FILE}?check=${Date.now()}`,{cache:'no-store',signal:controller.signal});clearTimeout(timeout);if(!response.ok)throw new Error('version check failed');const remote=await response.json();lastRemoteVersion=String(remote.version||'');if(rollbackActive){lastStatus='rollback'}else{lastStatus=lastRemoteVersion===APP_VERSION?'current':'update';if(lastStatus==='update')openUpdateModal()}render()}catch(_){if(rollbackActive)lastStatus='rollback';else if(navigator.onLine&&lastStatus!=='update')lastStatus='current';else lastStatus='offline';render()}finally{versionCheckInFlight=false}}
function escapeHtml(value){return String(value??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]||c))}
function maybeShowDeferredUpdate(){if(updateDeferred&&!isAppBusy()&&(lastStatus==='update'||lastStatus==='rollback')){updateDeferred=false;openUpdateModal()}}
installStyles();render();
window.addEventListener('online',checkVersion);window.addEventListener('offline',()=>{lastStatus=rollbackActive?'rollback':'offline';render();removeModal(MODAL_ID)});
window.addEventListener('error',(event)=>{if(!isAppBusy())openRecoveryModal(event?.message||'Neočekávaná chyba aplikace.');});
window.addEventListener('unhandledrejection',(event)=>{if(!isAppBusy())openRecoveryModal(event?.reason?.message||'Neočekávaná chyba aplikace.');});
setTimeout(checkVersion,500);setInterval(checkVersion,5*60*1000);setInterval(maybeShowDeferredUpdate,2000);
